//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int Student_Id { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string YearResult { get; set; }
        public Nullable<int> SectionSection_Id { get; set; }
    
        public virtual Sections Sections { get; set; }
    }
}
