//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_Sales_for_1997
    {
        public string CategoryName { get; set; }
        public Nullable<decimal> CategorySales { get; set; }
    }
}
